[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
