name = "FUSE"
uuid = "e64856f0-3bb8-4376-b4b7-c03396503992"
authors = ["Orso Meneghini <orso82@gmail.com>"]
version = "0.8.7"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BalanceOfPlantSurrogate = "001e48cb-5a1e-4e3c-a5d4-cdc3aa14f3de"
BoundaryPlasmaModels = "2da5b0d0-c5e5-4f14-9caf-62d0020df410"
CHEASE = "40781a8e-f1bb-11ec-24ef-0f6bc40c1567"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EGGO = "25cd7528-e4e3-46fe-8df7-7ec8e1454e14"
EPEDNN = "e64856f0-3bb8-4376-b4b7-c03396503991"
FRESCO = "f2db6eb9-2c54-4c18-912b-ce467796777a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointAcceleration = "817d07cb-a79a-5c30-9a31-890123675176"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
FusionMaterials = "4c86da02-02c8-4634-8460-96566129f8e0"
GACODE = "bb074124-7a58-47ce-bd41-6b7098184f23"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HelpPlots = "5880b2e8-ad0a-48c9-bacd-30dc9c1357e0"
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
IMASutils = "b8e4ee59-9bed-3a6a-a553-8dd24d6374ad"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JpegTurbo = "b835a17e-a41a-41e7-81f0-2f016b05efe0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MXHEquilibrium = "8efa4e5a-7b9a-4eec-876e-01d13d5b5d75"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NNeutronics = "a9424c20-d414-11ec-167b-9106c24d956c"
NeoclassicalTransport = "e630bb45-bea9-4e62-953e-b44d0741ac01"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PAM = "8217f67a-9bf0-495c-a6dc-30c3fb73287a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QED = "8bcbec86-48c7-11ec-16a6-c1bc83299373"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RABBIT = "98960a00-302f-469e-9595-275b70d10766"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SimulationParameters = "32ab26d3-25d6-405d-a295-367385e16093"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TEQUILA = "a60c9cbd-e72f-4185-96b6-b8fc312c4d37"
TJLF = "12ecd31c-256b-4db5-a799-cd5afeb0bd7d"
TORBEAM = "b9bf819a-2a49-451a-b482-4ce9066e62e1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TroyonBetaNN = "c0158764-c6e1-428b-a545-31826f389bc8"
TurbulentTransport = "9bf5e8f4-5746-4003-bc69-ef83265c10ca"
VacuumFields = "9d9223b5-c5da-4bf4-abee-2a8bb6775a49"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
ThermalSystemModels = "68b8b4ac-b179-4f07-8ae9-c1f1360acbca"

[extensions]
ThermalSystemModelsExt = "ThermalSystemModels"

[compat]
AbstractTrees = "0.4"
BalanceOfPlantSurrogate = "3"
BoundaryPlasmaModels = "1"
CHEASE = "1"
CSV = "0.10"
ClusterManagers = "0.4"
DataFrames = "1"
DelimitedFiles = "1"
EGGO = "2.0"
EPEDNN = "1"
FRESCO = "0.3, 0.4"
FileIO = "1"
FixedPointAcceleration = "1.0.1"
ForwardDiff = "0.10"
FusionMaterials = "1"
GACODE = "1"
GeoInterface = "1"
HDF5 = "0.17.2"
HelpPlots = "1"
IMAS = "5.4.4"
IMASutils = "1.5.1"
Interpolations = "0.15, 0.16.1"
JSON = "0.21"
JpegTurbo = "0.1"
LaTeXStrings = "1"
LibGEOS = "0.9"
LoggingExtras = "1"
MXHEquilibrium = "1"
Measurements = "2"
Memoize = "0.4"
Metaheuristics = "3"
NeoclassicalTransport = "1"
NLsolve = "4"
NNeutronics = "1"
NonlinearSolve = "4.8.0"
Optim = "1"
OrderedCollections = "1"
Plots = "1"
PolygonOps = "0.1"
ProgressMeter = "1"
QED = "1.5"
QuadGK = "2"
RABBIT = "2"
Serialization = "1.11.0"
SimulationParameters = "2"
SnoopPrecompile = "1"
SpecialFunctions = "2"
StaticArrays = "1"
TEQUILA = "1"
TJLF = "1"
TORBEAM = "1"
Test = "1"
ThermalSystemModels = "1"
TimerOutputs = "0.5"
TroyonBetaNN = "1"
TurbulentTransport = "1"
VacuumFields = "4"
Weave = "0.10"
YAML = "0.4"
