name = "FUSE"
uuid = "e64856f0-3bb8-4376-b4b7-c03396503992"
authors = ["Orso Meneghini <orso82@gmail.com>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
CoordinateConventions = "7204ce3a-f536-43d2-be4a-fbed74e90d86"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EFIT = "cda752c5-6b03-55a3-9e33-132a441b0c17"
EPEDNN = "e64856f0-3bb8-4376-b4b7-c03396503991"
Equilibrium = "187daef3-cca3-527a-8725-7379bc760182"
FiniteElementHermite = "6ce10167-d368-4c0e-af34-9787cdd175e5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
FusionMaterials = "4c86da02-02c8-4634-8460-96566129f8e0"
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
IMASDD = "06b86afa-9f21-11ec-2ef8-e51b8960cfc5"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QED = "8bcbec86-48c7-11ec-16a6-c1bc83299373"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TAUENN = "4f5ffc88-c87f-11eb-142e-4d2ba0394a67"
TGLFNN = "558c7b13-fd9f-4806-b461-592296cfa9d0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VacuumFields = "9d9223b5-c5da-4bf4-abee-2a8bb6775a49"
