[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CHEASE = "40781a8e-f1bb-11ec-24ef-0f6bc40c1567"
CoordinateConventions = "7204ce3a-f536-43d2-be4a-fbed74e90d86"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EPEDNN = "e64856f0-3bb8-4376-b4b7-c03396503991"
FUSE = "e64856f0-3bb8-4376-b4b7-c03396503992"
FiniteElementHermite = "6ce10167-d368-4c0e-af34-9787cdd175e5"
Fortran90Namelists = "8fb689aa-71ff-4044-8071-0cffc910b57d"
FusionGeometryTools = "01d32d46-7344-4277-b61f-8ab77e9dcb51"
FusionMaterials = "4c86da02-02c8-4634-8460-96566129f8e0"
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
IMASDD = "06b86afa-9f21-11ec-2ef8-e51b8960cfc5"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MXHEquilibrium = "8efa4e5a-7b9a-4eec-876e-01d13d5b5d75"
MeshTools = "804828d9-b4e9-4eca-b847-748d6c7bafa9"
MillerExtendedHarmonic = "c82744c2-dc08-461a-8c37-87ab04d0f9b8"
NNeutronics = "a9424c20-d414-11ec-167b-9106c24d956c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlasmaFacingSurfaces = "c15cc0b6-2357-461f-989f-fb182449c7ff"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QED = "8bcbec86-48c7-11ec-16a6-c1bc83299373"
SimulationParameters = "32ab26d3-25d6-405d-a295-367385e16093"
TAUENN = "4f5ffc88-c87f-11eb-142e-4d2ba0394a67"
TEQUILA = "a60c9cbd-e72f-4185-96b6-b8fc312c4d37"
TGLFNN = "558c7b13-fd9f-4806-b461-592296cfa9d0"
VacuumFields = "9d9223b5-c5da-4bf4-abee-2a8bb6775a49"
